---
title: "Computing Assignment VII"
author: "The Franciscans"
date: "March 9, 2018"
output: ioslides_presentation
smaller: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(knitr)
library(tidyverse)
library(AER)
library(matlib)
library(kableExtra)
```

```{r message=FALSE, warning=FALSE}
remove(list = ls())

#data
data_RS <- read_csv("https://raw.githubusercontent.com/ucdavis/ARE_ECON_240A_2018/master/Computing_Assignment_VII/data/RSdata.csv")
```

```{r include=FALSE}
# OLS supply incl ln_w
OLS_supply <- lm(ln_qs~ln_fp + ln_w + trendsp1 + trendsp2 + trendsp3, data=data_RS)
summary(OLS_supply)
  # Coefficient on ln_fp (8.876e-02) same sign, but significant (t=7.628) and half the magnitude

# OLS supply excl ln_w
OLS_supply_exclw <- lm(ln_qs~ln_fp + trendsp1 + trendsp2 + trendsp3, data=data_RS)
summary(OLS_supply_exclw)

# OLS demand
OLS_demand <- lm(ln_qd~ln_sp + trendsp1 + trendsp2 + trendsp3, data=data_RS)
summary(OLS_demand)
  # Coefficient on ln_sp same sign, similar magnitude, but insignificant
```

```{r include=FALSE}
IV_supply <- ivreg(ln_qs ~ ln_fp + ln_w + trendsp1 + trendsp2 + trendsp3 | lag(ln_w) + ln_w + trendsp1 + trendsp2 + trendsp3, data=data_RS)
summary(IV_supply)
  # Coefficient same sign and similar magnitude, standard error also similar (0.101652)

IV_supply_exclw <- ivreg(ln_qs ~ ln_fp + trendsp1 + trendsp2 + trendsp3 | lag(ln_w) + ln_w + trendsp1 + trendsp2 + trendsp3, data=data_RS)
summary(IV_supply_exclw)

IV_demand <- ivreg(ln_qd ~ ln_sp + trendsp1 + trendsp2 + trendsp3 | ln_w + trendsp1 + trendsp2 + trendsp3, data=data_RS)
summary(IV_demand)
  # Coefficient on ln_sup same sign, similar magnitude, similar standard error
```

## Estimate OLS and IV: full model {.smaller}

```{r}
kable(cbind(summary(OLS_supply)$coefficients,summary(IV_supply)$coefficients), caption = "Supply", digits = 3, format = "html") %>%
  kable_styling(full_width = F) %>%
  add_header_above(c(" ", "OLS" = 4, "IV" = 4))

kable(cbind(summary(OLS_demand)$coefficients,summary(IV_demand)$coefficients), caption = "Demand", digits = 3, format = "html") %>%
  kable_styling(full_width = F) %>%
  add_header_above(c(" ", "OLS" = 4, "IV" = 4))
```

## Estimate OLS and IV: ln_w as instrument only {.smaller}
```{r}
kable(cbind(summary(OLS_supply_exclw)$coefficients,summary(IV_supply_exclw)$coefficients), caption = "Supply", digits = 3, format = "html") %>%
  kable_styling(full_width = F) %>%
  add_header_above(c(" ", "OLS" = 4, "IV" = 4))
```

## Hausman tests for supply model 
```{r include=FALSE}
# full model including ln_w
beta_diff <- coefficients(OLS_supply) - coefficients(IV_supply)
cov_diff <- vcov(IV_supply) - vcov(OLS_supply)
Hs = t(beta_diff) %*% Ginv(cov_diff) %*% beta_diff
Hs

# model excluding ln_w -- how do we do this when the matrices are different sizes?? 
beta_diff_exclw <- coefficients(OLS_supply_exclw) - coefficients(IV_supply_exclw)
cov_diff_exclw <- vcov(IV_supply_exclw) - vcov(OLS_supply_exclw)
Hs_exclw = t(beta_diff_exclw) %*% Ginv(cov_diff_exclw) %*% beta_diff_exclw
Hs_exclw
```

```{r echo=FALSE}
kable(t(c(Hs, Hs_exclw)), col.names = c("Full model", "Without ln_w"), digits = 3, caption = "Hausman tests for OLS vs. IV", format = "html") %>%
  kable_styling(full_width = F) 
```

 
## Supply model w/ area instead of total quantity {.smaller}
```{r include=FALSE}
data_RS <- mutate(data_RS, ln_area = log(area))

OLS_supply_area <- lm(ln_area~ln_fp + ln_w + trendsp1 + trendsp2 + trendsp3, data=data_RS)
summary(OLS_supply_area)

IV_supply_area <- ivreg(ln_area~ln_fp + ln_w + trendsp1 + trendsp2 + trendsp3 | lag(ln_w) + ln_w + trendsp1 + trendsp2 + trendsp3, data=data_RS)
summary(IV_supply_area)
```

```{r echo=FALSE}
kable(cbind(summary(OLS_supply_area)$coefficients,summary(IV_supply_area)$coefficients), caption = "Supply", digits = 3, format = "html") %>%
  kable_styling(full_width = F) %>%
  add_header_above(c(" ", "OLS" = 4, "IV" = 4))
```

## Comments about canvas vs. RS dataset {.smaller}