---
title: "Assignment V"
author: "YEP"
date: "2/22/2018"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

##  Variance of the 3 estimators
$$\beta=0$$
Variance of the true model is smaller
```{r }
library(dplyr)
library(ggplot2)
library(broom)
library(MASS)
library(lmtest)
library(knitr)
set.seed(10101)
sigma <- matrix(c(1,0.7,0.7,1),nrow=2)

dgp0 <- function(n,beta){
  
  x <-mvrnorm(n, mu=c(0,0), Sigma=sigma)
  e <-rnorm(n)
  y <- 0.2*x[,1]+beta*x[,2]+e
  
  data0 <- data.frame(cbind(x,e,y))
  
  reg.res <- lm(y~V1 -1, data=data0)
  reg.unres <- lm(y~V1 + V2 -1, data=data0)
  test.res <- 0.2>confint(reg.res)["V1",1] & 0.2<confint(reg.res)["V1", 2]
  test.unres <- 0.2>confint(reg.unres)["V1",1] & 0.2<confint(reg.unres)["V1", 2]
  alpha.res <- coef(reg.res)[1]
  alpha.unres <- coef(reg.unres)[1]
  p.value <- tidy(reg.unres)[2,5]
  selected <- if(p.value<0.05){c(alpha.unres,tidy(reg.unres)[1,5],test.unres)
  }else{
      c(alpha.res,tidy(reg.res)[1,5],test.res)}
  
  res <- cbind(n, beta, alpha.unres,alpha.res,test.unres,test.res,p.value,t(selected))
  res <- as.data.frame(res)
  return(res)
}

S <- 2000
params_gr0 <-expand.grid(1:S, n=c(50,100,150,200) ,beta=c(0, 0.16, 0.24, 0.5))
res_gr0 <-mapply(dgp0, n=params_gr0$n, beta=params_gr0$beta,  SIMPLIFY = FALSE) %>%
  bind_rows() %>%
  as_data_frame()

a <- res_gr0 %>% filter(beta==0) %>% group_by(n) %>% 
  summarise(var(alpha.res),var(alpha.unres),var(V1))
colnames(a) <- c("n", "Alpha Res.", "Alpha Unres.", "Pos")
kable(a, digits = 3)
```

##  Bias of the 3 estimators
Restricted model is biased
$$\alpha_{res} =\alpha_{unres} +E[x'_{1}x_{1}]^{-1}*E[x'_{1}x_{2}]*\beta=\alpha_{unres} +0.7\beta $$
```{r }
b <- res_gr0 %>% filter(beta!=0) %>% group_by(beta,n) %>% 
  summarise(mean(alpha.res)-0.2,mean(alpha.unres)-0.2,mean(V1)-0.2)
colnames(b)<- c("Beta", "n", "Alpha Res.", "Alpha Unres.", "Alpha Pos")
kable(b, digits = 3)
```

## 
 Average times where alpha is in the confidence interval
```{r }
c <- res_gr0 %>% group_by(beta,n) %>% 
  summarise(mean(test.res),mean(test.unres),mean(V10))
colnames(c)<- c("Beta", "n", "Mean Res.", "Mean Unres.", "Mean Pos")
kable(c, digits = 3)
```

##  Density of standardized distribution
 
```{r }
res_gr0 <- res_gr0 %>% mutate(dens.res=sqrt(n)*(alpha.res-0.2),
                              dens.unres=sqrt(n)*(alpha.unres-0.2),
                              dens.ed=sqrt(n)*(V1-0.2)) 



ggplot(res_gr0) +
  geom_density(aes(x=dens.res, color="Restricted"))+
  geom_density(aes(x=dens.unres))+ 
  facet_grid(n~beta)+
  theme_bw() 
```

##  Density of standardized distribution
 
```{r }
ggplot(res_gr0) +
  geom_density(aes(x=dens.res, color="Restricted"))+
  geom_density(aes(x=dens.unres), linetype="dotted")+ 
  geom_density(aes(x=dens.ed, fill="Post-selection" ,  alpha=0.5))+ 
  facet_grid(n~beta)+
  theme_bw() 
```

##  Percentage of rejection of the t-test for beta
 
```{r }
d <- res_gr0 %>%  
  mutate(beta.test=(p.value<0.05)) %>% 
  group_by(n,beta) %>% 
  summarize(mean(beta.test))
kable(d, digits = 3)
```