---
title: "Computing Assignment VII"
author: "group"
date: "March 9, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## your document
```{r}
rm(list = ls())           # clean the workspace
library(ggplot2)          # use read_dta
library(tidyverse)        # data cleaning packages
library(broom)
library(lmtest)
library(MASS)
library(dplyr)
library(AER)
```
# load data
```{r data}
data0 <- read.csv("C:/Users/Manho/Documents/UCDavis/Econ/18_Winter/240A/HW/hw7/RSdata.csv")
data <- data.frame(sapply(data0, function(x) as.numeric(as.character(x))))
data <- data %>% mutate(lag_ln_w = dplyr::lag(ln_w))
```
## run OLS

```{r regression}
# OLS supply w/o ln_w
reg_s <- lm(ln_qs ~ ln_fp + trendsp1+trendsp2+trendsp3, data=data)
b_ols<-coeftest(reg_s)[,1]%>%
  as.matrix() 

# OLS supply w/ ln_w
reg_s_w <- lm(ln_qs ~ ln_fp + ln_w + trendsp1+trendsp2+trendsp3, data=data)
b_ols_w<-coeftest(reg_s_w)[,1] %>%
  as.matrix()

# OLS demand
reg_d <- lm(ln_qd ~ ln_sp + trendsp1+trendsp2+trendsp3, data=data)
b_ols_d<-coeftest(reg_d)[,1] %>%
  as.matrix()

## run IV reg

# IV w/o ln_w
reg_s_iv <-ivreg(ln_qs ~ ln_fp + trendsp1+trendsp2+trendsp3, ~lag_ln_w + trendsp1+trendsp2+trendsp3, data)
coeftest(reg_s_iv)
b_iv<-coeftest(reg_s_iv)[,1] %>%
  as.matrix()

# IV w ln_w
reg_s_iv_w <-ivreg(ln_qs ~ ln_fp + ln_w + trendsp1+trendsp2+trendsp3, ~lag_ln_w + ln_w+trendsp1+trendsp2+trendsp3, data)
coeftest(reg_s_iv_w)
b_iv_w<-coeftest(reg_s_iv_w)[,1] %>%
  as.matrix()

reg_d_iv <-ivreg(ln_qd ~ ln_sp + trendsp1+trendsp2+trendsp3, ~ln_w+trendsp1+trendsp2+trendsp3, data)
coeftest(reg_d_iv)
```

# Hausman test
```{r Hausman}
H <- t(b_iv-b_ols)%*%solve(vcov(reg_s_iv)-vcov(reg_s))%*%(b_iv-b_ols)
H_w <- t(b_iv_w-b_ols_w)%*%solve(vcov(reg_s_iv_w)-vcov(reg_s_w))%*%(b_iv_w-b_ols_w)

pchisq(H,df=5)
pchisq(H_w,df=5)
```

# supply elasticity for area, yield
```{r supply}
reg_s_ay <- lm(ln_qs ~ log(area) + log(yield_shock), data=data)
coeftest(reg_s_ay)
```